return {
    label = "Doors",
    hidden = false,

    list = {
        {
            label = "Door Weazel",
            model = "prop_bh1_09_mp_l",
            price = 500,
            type = 'door',
        },
        {
            label = "Deviant Front Door",
            model = "v_ilev_deviantfrontdoor",
            price = 500,
            type = 'door',
        },
        {
            label = "LS custom door",
            model = "prop_com_ls_door_01",
            price = 500,
            type = 'door',
        },
        {
            label = "Office door 1",
            model = "ex_p_mp_door_office_door01_s",
            price = 500,
            type = 'door',
        },
        {
            label = "Office door 2",
            model = "v_ilev_cor_darkdoor",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 1",
            model = "v_ilev_sol_off_door01",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 2",
            model = "prop_grumandoor_r",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 3",
            model = "hei_heist_apart2_door",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 4",
            model = "prop_ret_door_04",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 5",
            model = "v_ilev_housedoor1",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 6",
            model = "ch_prop_ch_vault_slide_door_sm",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 7",
            model = "ch_prop_casino_door_01e",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 8",
            model = "v_ilev_ml_door1",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 9",
            model = "p_cut_door_03",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 10",
            model = "prop_motel_door_09",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 11",
            model = "prop_ld_bankdoors_02",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 12",
            model = "sum_p_mp_yacht_door",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 13",
            model = "prop_barn_door_r",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 14",
            model = "v_ilev_abbmaindoor",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 15",
            model = "xm_prop_lab_door01_r",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 16",
            model = "hei_prop_hei_bankdoor_new",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 17",
            model = "apa_v_ilev_ss_door2",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 18",
            model = "prop_epsilon_door_r",
            price = 500,
            type = 'door',
        },
        {
            label = "Door 19",
            model = "vw_prop_vw_door_lounge_01a",
            price = 500,
            type = 'door',
        },
    }
}
