if not Config.DatabaseChecker?.Enabled then
    return
end

local defaultTables = {
	lbtablet_police_accounts = {
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "display_name",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "avatar",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "callsign",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 10,
		},
	},
	lbtablet_chat_rooms = {
		{
			column = "private",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "terminal_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "last_updated",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "last_message",
			type = "TEXT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "creator",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "label",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "icon",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
	},
	lbtablet_ambulance_reports_doctors = {
		{
			column = "doctor",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_ambulance_tags = {
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "color",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 10,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "tag_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 20,
		},
	},
	lbtablet_ambulance_reports_conditions = {
		{
			column = "condition_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_ambulance_profile_conditions = {
		{
			column = "profile_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "condition_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_warrants = {
		{
			column = "linked_profile_type",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "warrant_status",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			default = "'active'",
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "description",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "priority",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			default = "'low'",
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "updated_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "warrant_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "linked_profile_id",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_photo_albums = {
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "tablet_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_police_profiles = {
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "avatar",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "profile_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			default = "'player'",
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "notes",
			type = "TEXT",
			allowNull = false,
			isKey = false,
			default = "''",
			collation = "utf8mb4_unicode_ci",
		},
	},
	lbtablet_police_warrants_attachments = {
		{
			column = "attachment",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "warrant_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_bulletin = {
		{
			column = "content",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "pinned",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_ambulance_accounts = {
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "display_name",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "avatar",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "callsign",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 10,
		},
	},
	lbtablet_ambulance_profiles = {
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "avatar",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "notes",
			type = "TEXT",
			allowNull = false,
			isKey = false,
			default = "''",
			collation = "utf8mb4_unicode_ci",
		},
	},
	lbtablet_notifications = {
		{
			column = "content",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "avatar",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "tablet_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "thumbnail",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "show_avatar",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "app",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "received_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
	},
	lbtablet_police_jail = {
		{
			column = "related_case",
			type = "INT",
			allowNull = true,
			isKey = true,
			default = "NULL",
		},
		{
			column = "jail_time",
			type = "INT",
			allowNull = false,
			isKey = false,
		},
		{
			column = "reason",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "original_time",
			type = "INT",
			allowNull = false,
			isKey = false,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "jailed_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "jailed_by",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "prisoner",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_police_offences = {
		{
			column = "category_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "jail_time",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "fine",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "description",
			type = "TEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
		},
		{
			column = "class",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_ambulance_bulletin = {
		{
			column = "content",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "pinned",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_police_cases_involved = {
		{
			column = "case_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "involvement",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "involved",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_ambulance_conditions = {
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "category_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "severity",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 25,
		},
	},
	lbtablet_ambulance_profile_tags = {
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "tag_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_voice_memo_recordings = {
		{
			column = "file_url",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "file_name",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "created_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "tablet_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "file_length",
			type = "INT",
			allowNull = false,
			isKey = false,
		},
	},
	lbtablet_tablets = {
		{
			column = "is_setup",
			type = "TINYINT",
			allowNull = true,
			isKey = false,
			default = "0",
		},
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "tablet_name",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "settings",
			type = "LONGTEXT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
		},
		{
			column = "battery",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "100",
		},
	},
	lbtablet_police_weapons = {
		{
			column = "serial_number",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "weapon_name",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "owner",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_police_offences_categories = {
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_police_warrants_tags = {
		{
			column = "tag_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "warrant_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_warrants_linked_reports = {
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "warrant_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_tags = {
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "color",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 10,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
	},
	lbtablet_police_cases_criminals = {
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "case_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "jail_time",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "fine",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
	},
	lbtablet_police_cases_tags = {
		{
			column = "tag_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "case_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_reports_tags = {
		{
			column = "tag_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_reports_involved = {
		{
			column = "involvement",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "involved",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_chat_rooms_messages = {
		{
			column = "message",
			type = "TEXT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
		},
		{
			column = "author",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "room_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "attachments",
			type = "TEXT",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
		},
		{
			column = "sent_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
	},
	lbtablet_police_cases_evidence = {
		{
			column = "attachment",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "case_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_reports_attachments = {
		{
			column = "attachment",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_notes = {
		{
			column = "content",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "tablet_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "updated_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
	},
	lbtablet_police_reports = {
		{
			column = "updated_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "description",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "report_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_police_profile_tags = {
		{
			column = "id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "tag_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_logs = {
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "content",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "log_action",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "log_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "related_id",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "log_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_ambulance_reports_attachments = {
		{
			column = "attachment",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_photo_album_photos = {
		{
			column = "photo_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "album_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_police_cases = {
		{
			column = "updated_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "closed",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "description",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
	},
	lbtablet_ambulance_logs = {
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "content",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "log_action",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 25,
		},
		{
			column = "log_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "related_id",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "log_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_ambulance_reports_tags = {
		{
			column = "tag_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "report_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_photos = {
		{
			column = "created_at",
			type = "TIMESTAMP",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "is_favourite",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "metadata",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 20,
		},
		{
			column = "size",
			type = "FLOAT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "tablet_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "link",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 500,
		},
		{
			column = "is_video",
			type = "TINYINT",
			allowNull = true,
			isKey = false,
			default = "0",
		},
	},
	lbtablet_clock_alarms = {
		{
			column = "hours",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "label",
			type = "VARCHAR",
			allowNull = true,
			isKey = false,
			default = "NULL",
			collation = "utf8mb4_unicode_ci",
			length = 50,
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "enabled",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "1",
		},
		{
			column = "tablet_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "minutes",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
	},
	lbtablet_apps_loggedin = {
		{
			column = "account",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "active",
			type = "TINYINT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "tablet_id",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "app",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 25,
		},
	},
	lbtablet_ambulance_conditions_categories = {
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
	lbtablet_police_cases_charges = {
		{
			column = "criminal",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "case_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "offence_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_chat_rooms_members = {
		{
			column = "account",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "notifications",
			type = "INT",
			allowNull = false,
			isKey = false,
			default = "0",
		},
		{
			column = "room_id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
	},
	lbtablet_ambulance_reports = {
		{
			column = "updated_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "report_type",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "title",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_at",
			type = "DATETIME",
			allowNull = false,
			isKey = false,
			default = "current_timestamp()",
		},
		{
			column = "id",
			type = "INT",
			allowNull = false,
			isKey = true,
		},
		{
			column = "description",
			type = "MEDIUMTEXT",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 16777215,
		},
		{
			column = "patient",
			type = "VARCHAR",
			allowNull = false,
			isKey = false,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
		{
			column = "created_by",
			type = "VARCHAR",
			allowNull = false,
			isKey = true,
			collation = "utf8mb4_unicode_ci",
			length = 100,
		},
	},
}

function GetDefaultDatabaseTables()
    return defaultTables
end
